#!/bin/bash
./all_repos_log.sh \
/root/devstats_repos/Azure/* \
/root/devstats_repos/BendingBender/* \
/root/devstats_repos/BuoyantIO/* \
/root/devstats_repos/DataTables/* \
/root/devstats_repos/EnMasseProject/* \
/root/devstats_repos/FasterXML/* \
/root/devstats_repos/FortAwesome/* \
/root/devstats_repos/GoogleCloudPlatform/* \
/root/devstats_repos/Gozala/* \
/root/devstats_repos/JamesNK/* \
/root/devstats_repos/JedWatson/* \
/root/devstats_repos/JohnPostlethwait/* \
/root/devstats_repos/Modernizr/* \
/root/devstats_repos/NetworkServiceMesh/* \
/root/devstats_repos/OpenBMP/* \
/root/devstats_repos/OpenObservability/* \
/root/devstats_repos/OverZealous/* \
/root/devstats_repos/Raynos/* \
/root/devstats_repos/ReactTraining/* \
/root/devstats_repos/RichiH/* \
/root/devstats_repos/Virtual-Kubelet/* \
/root/devstats_repos/acornjs/* \
/root/devstats_repos/ahmadnassri/* \
/root/devstats_repos/alexellis/* \
/root/devstats_repos/alibaba/* \
/root/devstats_repos/angular-translate/* \
/root/devstats_repos/angular-ui/* \
/root/devstats_repos/angular/* \
/root/devstats_repos/apache/* \
/root/devstats_repos/apcera/* \
/root/devstats_repos/appc/* \
/root/devstats_repos/ashtuchkin/* \
/root/devstats_repos/auth0/* \
/root/devstats_repos/awslabs/* \
/root/devstats_repos/axios/* \
/root/devstats_repos/beanvalidation/* \
/root/devstats_repos/beatgammit/* \
/root/devstats_repos/bestiejs/* \
/root/devstats_repos/brigadecore/* \
/root/devstats_repos/brix/* \
/root/devstats_repos/broofa/* \
/root/devstats_repos/browserify/* \
/root/devstats_repos/buildpack/* \
/root/devstats_repos/calvinmetcalf/* \
/root/devstats_repos/caolan/* \
/root/devstats_repos/cdfoundation/* \
/root/devstats_repos/chalk/* \
/root/devstats_repos/chubaofs/* \
/root/devstats_repos/cloudevents/* \
/root/devstats_repos/cncf/* \
/root/devstats_repos/containerd/* \
/root/devstats_repos/containerfs/* \
/root/devstats_repos/containerfilesystem/* \
/root/devstats_repos/containernetworking/* \
/root/devstats_repos/coredns/* \
/root/devstats_repos/coreos/* \
/root/devstats_repos/cortexproject/* \
/root/devstats_repos/cri-o/* \
/root/devstats_repos/crosscloudci/* \
/root/devstats_repos/datawire/* \
/root/devstats_repos/davepacheco/* \
/root/devstats_repos/devongovett/* \
/root/devstats_repos/docker/* \
/root/devstats_repos/dotnet/* \
/root/devstats_repos/dougwilson/* \
/root/devstats_repos/dragonflyoss/* \
/root/devstats_repos/draios/* \
/root/devstats_repos/eclipse-ee4j/* \
/root/devstats_repos/envoyproxy/* \
/root/devstats_repos/epoberezkin/* \
/root/devstats_repos/ericbottard/* \
/root/devstats_repos/etcd-io/* \
/root/devstats_repos/etcd/* \
/root/devstats_repos/expressjs/* \
/root/devstats_repos/facebook/* \
/root/devstats_repos/falcosecurity/* \
/root/devstats_repos/felixge/* \
/root/devstats_repos/feross/* \
/root/devstats_repos/fluent/* \
/root/devstats_repos/fluxcd/* \
/root/devstats_repos/fnhub/* \
/root/devstats_repos/fnproject/* \
/root/devstats_repos/form-data/* \
/root/devstats_repos/goharbor/* \
/root/devstats_repos/google/* \
/root/devstats_repos/gotwarlost/* \
/root/devstats_repos/graphql/* \
/root/devstats_repos/grpc/* \
/root/devstats_repos/gulpjs/* \
/root/devstats_repos/hapijs/* \
/root/devstats_repos/helm/* \
/root/devstats_repos/hueniverse/* \
/root/devstats_repos/hughsk/* \
/root/devstats_repos/improbable-eng/* \
/root/devstats_repos/in-toto/* \
/root/devstats_repos/iovisor/* \
/root/devstats_repos/isaacs/* \
/root/devstats_repos/istio/* \
/root/devstats_repos/jaegertracing/* \
/root/devstats_repos/janvanhelvoort/* \
/root/devstats_repos/jaredhanson/* \
/root/devstats_repos/jashkenas/* \
/root/devstats_repos/jenkins-infra/* \
/root/devstats_repos/jenkins-x-apps/* \
/root/devstats_repos/jenkins-x-buildpacks/* \
/root/devstats_repos/jenkins-x-charts/* \
/root/devstats_repos/jenkins-x-quickstarts/* \
/root/devstats_repos/jenkins-x/* \
/root/devstats_repos/jenkinsci/* \
/root/devstats_repos/jldec/* \
/root/devstats_repos/jonschlinkert/* \
/root/devstats_repos/joyent/* \
/root/devstats_repos/jquery-validation/* \
/root/devstats_repos/jquery/* \
/root/devstats_repos/jshttp/* \
/root/devstats_repos/juliangruber/* \
/root/devstats_repos/kelektiv/* \
/root/devstats_repos/kennethreitz/* \
/root/devstats_repos/knative/* \
/root/devstats_repos/kubeedge/* \
/root/devstats_repos/kubernetes-client/* \
/root/devstats_repos/kubernetes-csi/* \
/root/devstats_repos/kubernetes-graveyard/* \
/root/devstats_repos/kubernetes-helm/* \
/root/devstats_repos/kubernetes-incubator-retired/* \
/root/devstats_repos/kubernetes-incubator/* \
/root/devstats_repos/kubernetes-retired/* \
/root/devstats_repos/kubernetes-security/* \
/root/devstats_repos/kubernetes-sig-testing/* \
/root/devstats_repos/kubernetes-sigs/* \
/root/devstats_repos/kubernetes/* \
/root/devstats_repos/kubevirt/* \
/root/devstats_repos/ligato/* \
/root/devstats_repos/linkerd/* \
/root/devstats_repos/ljharb/* \
/root/devstats_repos/lodash/* \
/root/devstats_repos/longhorn/* \
/root/devstats_repos/lyft/* \
/root/devstats_repos/madler/* \
/root/devstats_repos/mafintosh/* \
/root/devstats_repos/markfisher/* \
/root/devstats_repos/maxogden/* \
/root/devstats_repos/mcavage/* \
/root/devstats_repos/mde/* \
/root/devstats_repos/micromatch/* \
/root/devstats_repos/miekg/* \
/root/devstats_repos/mikeal/* \
/root/devstats_repos/mininet/* \
/root/devstats_repos/moment/* \
/root/devstats_repos/motdotla/* \
/root/devstats_repos/moxystudio/* \
/root/devstats_repos/mozilla/* \
/root/devstats_repos/mysql-net/* \
/root/devstats_repos/nanjingboy/* \
/root/devstats_repos/nats-io/* \
/root/devstats_repos/necolas/* \
/root/devstats_repos/networkservicemesh/* \
/root/devstats_repos/ng-bootstrap/* \
/root/devstats_repos/nodejs/* \
/root/devstats_repos/npm/* \
/root/devstats_repos/nunit/* \
/root/devstats_repos/omsmith/* \
/root/devstats_repos/open-faas/* \
/root/devstats_repos/open-policy-agent/* \
/root/devstats_repos/open-switch/* \
/root/devstats_repos/open-telemetry/* \
/root/devstats_repos/opencontainers/* \
/root/devstats_repos/opencord/* \
/root/devstats_repos/openebs/* \
/root/devstats_repos/openeventing/* \
/root/devstats_repos/openfaas/* \
/root/devstats_repos/opennetworkinglab/* \
/root/devstats_repos/opensecuritycontroller/* \
/root/devstats_repos/openssl/* \
/root/devstats_repos/opentracing/* \
/root/devstats_repos/p4lang/* \
/root/devstats_repos/petkaantonov/* \
/root/devstats_repos/pieroxy/* \
/root/devstats_repos/pillarjs/* \
/root/devstats_repos/pingcap/* \
/root/devstats_repos/pivotal-cf/* \
/root/devstats_repos/ppatierno/* \
/root/devstats_repos/projectkudu/* \
/root/devstats_repos/projectriff/* \
/root/devstats_repos/prometheus/* \
/root/devstats_repos/pvorb/* \
/root/devstats_repos/qos-ch/* \
/root/devstats_repos/que-etc/* \
/root/devstats_repos/rancher/* \
/root/devstats_repos/reduxjs/* \
/root/devstats_repos/request/* \
/root/devstats_repos/rkt/* \
/root/devstats_repos/rktproject/* \
/root/devstats_repos/robrich/* \
/root/devstats_repos/rook/* \
/root/devstats_repos/rvagg/* \
/root/devstats_repos/rzwitserloot/* \
/root/devstats_repos/salesforce/* \
/root/devstats_repos/sass/* \
/root/devstats_repos/scala/* \
/root/devstats_repos/sindresorhus/* \
/root/devstats_repos/spiffe/* \
/root/devstats_repos/spinnaker/* \
/root/devstats_repos/stefanprodan/* \
/root/devstats_repos/strimzi/* \
/root/devstats_repos/substack/* \
/root/devstats_repos/tektoncd/* \
/root/devstats_repos/telepresenceio/* \
/root/devstats_repos/thanos-io/* \
/root/devstats_repos/theupdateframework/* \
/root/devstats_repos/thlorenz/* \
/root/devstats_repos/tikv/* \
/root/devstats_repos/tj/* \
/root/devstats_repos/torvalds/* \
/root/devstats_repos/treeder/* \
/root/devstats_repos/tungstenfabric/* \
/root/devstats_repos/twbs/* \
/root/devstats_repos/types/* \
/root/devstats_repos/typicaljoe/* \
/root/devstats_repos/uber/* \
/root/devstats_repos/virtual-kubelet/* \
/root/devstats_repos/visionmedia/* \
/root/devstats_repos/vitessio/* \
/root/devstats_repos/vmware/* \
/root/devstats_repos/weaveworks/* \
/root/devstats_repos/wesleytodd/* \
/root/devstats_repos/winstonjs/* \
/root/devstats_repos/yargs/* \
/root/devstats_repos/youtube/* \
/root/devstats_repos/zeit/* \
/root/devstats_repos/zephyrproject-rtos/* \
/root/devstats_repos/zloirock/*
